jobs:
  - job: build
    pool:
      vmImage: 'Ubuntu 16.04'
    strategy:
      matrix:
        "Prod":
          MATHWORKS_LICENSING_ENDPOINT: prod
        "Stage":
          MATHWORKS_LICENSING_ENDPOINT: stage
        "Dev":
          MATHWORKS_LICENSING_ENDPOINT: dev
    steps:
      - task: InstallMATLAB@0
        env:
          MATHWORKS_LICENSING_ENDPOINT: $(MATHWORKS_LICENSING_ENDPOINT)
      - task: RunMATLABCommand@0
        inputs:
          command: assertSuccess(runtests())