version: 2.1

executors:
  default:
    machine:
      image: ubuntu-1604:201903-01

orbs:
  matlab: mathworks/matlab@0

jobs:
  test:
    executor: default
    parameters:
      MATHWORKS_LICENSING_ENDPOINT:
        type: string
        default: ''
      RELEASE:
        type: string
        default: ''
    environment:
      MATHWORKS_LICENSING_ENDPOINT: <<parameters.MATHWORKS_LICENSING_ENDPOINT>>
    steps:
      - checkout
      - matlab/install:
          release: <<parameters.RELEASE>>
      - matlab/run-command:
          command: version
      - matlab/run-tests

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              MATHWORKS_LICENSING_ENDPOINT: ["prod", "stage", "dev"]
              RELEASE: ['latest', 'R2020b', 'R2020a']